# Generated by Django 3.2.20 on 2023-08-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='approved',
        ),
    ]
